export const PACKAGE_TYPES = [
  'bottle',
  'strip',
  'sheet',
  'tube',
  'vial',
  'ampoule',
  'box',
  'pack',
  'piece',
  'bag',
  'jar',
  'can',
  'roll',
  'container',
  'carton',
  'pouch',
  'sachet',
  'packet',
  'bundle',
  'sack',
] as const

export const STOCK_UNITS = [
  'piece',
  'tablet',
  'capsule',
  'ml',
  'liter',
  'gm',
  'kg',
  'mg',
  'meter',
  'cm',
  'pair',
  'set',
  'unit',
] as const

export type PackageType = (typeof PACKAGE_TYPES)[number]
export type StockUnit = (typeof STOCK_UNITS)[number]

export const ALLOWED_UNITS_BY_PACKAGE_TYPE: Record<PackageType, StockUnit[]> = {
  bottle: ['ml', 'liter', 'mg', 'piece', 'tablet', 'capsule'],
  strip: ['piece', 'tablet', 'capsule'],
  sheet: ['piece', 'tablet', 'capsule'],
  tube: ['gm', 'mg', 'ml'],
  vial: ['ml', 'piece'],
  ampoule: ['ml', 'piece'],
  box: ['piece', 'tablet', 'capsule'],
  pack: ['piece'],
  piece: ['piece'],
  bag: ['kg', 'gm', 'piece'],
  jar: ['ml', 'liter', 'gm', 'mg'],
  can: ['ml', 'liter'],
  roll: ['meter'],
  container: ['piece', 'unit', 'ml', 'liter', 'kg', 'gm'],
  carton: ['piece', 'unit'],
  pouch: ['piece', 'gm', 'kg', 'ml', 'liter'],
  sachet: ['piece', 'gm', 'ml'],
  packet: ['gm', 'kg', 'piece'],
  bundle: ['piece'],
  sack: ['kg'],
}
