export enum TicketCategory {
  REPAIR_MAINTENANCE = 'REPAIR_MAINTENANCE',
  CONCIERGE = 'CONCIERGE',
  HOUSEKEEPING = 'HOUSEKEEPING',
  FOOD = 'FOOD',
  OTHER = 'OTHER',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum TicketActivityType {
  CREATED = 'CREATED',
  APPROVED = 'APPROVED',
  ASSIGNED = 'ASSIGNED',
  STATUS_CHANGE = 'STATUS_CHANGE',
  COMMENT_ADDED = 'COMMENT_ADDED',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  PRIORITY_CHANGE = 'PRIORITY_CHANGE',
  UPDATED = 'UPDATED',
}
